-- NoBC apply scoring model - seed 15 scored QuestionDefinitions.
-- Target workspace: cmpd6xckn000004jl47xpwghx
-- Idempotent + transactional. Safe to re-run (template upserts, questions are
-- replaced). Paste into the Neon Console SQL editor against PROD.
BEGIN;

-- 1. Template (upsert by (workspaceId, slug))
INSERT INTO "ApplicationTemplate"
  (id, "workspaceId", name, description, slug, "isActive", "isDefault",
   "scoringInstructions", "archetypesEnabled", "memberWorthEnabled", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', 'Membership Application', 'The default No Bad Company membership application.', 'membership',
   true, true, 'Score this applicant on genuine fit for No Bad Company - a premium, curated members club in Austin. Reward specificity, evidence of building and connecting, real generosity, and authentic contribution to community over polish, status, or credentials. Thin, generic, or status-signaling answers score low. Apply each question''s own scoring logic and weight faithfully.', true, true, now(), now())
ON CONFLICT ("workspaceId", slug) DO UPDATE
  SET name = EXCLUDED.name, "isActive" = true, "isDefault" = true,
      "scoringInstructions" = EXCLUDED."scoringInstructions", "updatedAt" = now();

-- 2. Replace this template's questions (idempotent re-seed)
DELETE FROM "QuestionDefinition" WHERE "templateId" = (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership');

-- 3. Insert the 15 scored questions
INSERT INTO "QuestionDefinition"
  (id, "workspaceId", "templateId", "stableKey", label, type, section, "order", required, "isActive",
   "insightLabel", "insightDescription", "scoringDimension", "scoringWeight", "scoringLogic",
   "archetypeSignals", "sponsorRelevance", "createdAt", "updatedAt")
VALUES
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'whatYouDo', 'What do you do?', 'long_text', 'who-you-are', 1, false, true, 'what they do / what they build', 'Primary work - ownership, and whether they build, ship, or back something.', 'influence', 0.9, 'Work that builds, ships, or backs something scores high; ownership over title; vague "employed by" low.', ARRAY['Builder', 'Patron']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'comeToYouFor', 'What do people consistently come to you for?', 'long_text', 'how-you-move', 2, false, true, 'what people rely on them for', 'ANCHOR - the answer itself drives the archetype.', 'influence', 1, 'ANCHOR. The content decides: intros to Connector, advice/perspective to Sage, showing-up/backing to Patron, building help to Builder, tending people to Host, energy/fun to Spark. Specific repeated reliance scores high; generic scores low.', ARRAY['Connector', 'Host', 'Builder', 'Patron', 'Sage', 'Spark']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'characteristicsGoodAtJob', 'What characteristics make you good at your job?', 'long_text', 'who-you-are', 3, false, true, 'traits that make them good at their work', 'Execution/ownership traits vs perception/judgment traits - Builder vs Sage tell.', 'influence', 0.6, 'Execution/ownership traits point to Builder; perception/judgment/reading-people traits point to Sage. Concrete self-knowledge high; cliché low.', ARRAY['Builder', 'Sage']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'creativePursuits', 'Creative Pursuits and Passion Projects', 'long_text', 'who-you-are', 4, false, true, 'creative pursuits outside work', 'Active making/building vs pure consumption.', 'activation', 0.5, 'Active making/building outside work scores high; pure consumption scores low.', ARRAY['Builder']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'obsessedWith', 'What''s something you''ve become obsessed with?', 'long_text', 'how-you-move', 5, false, true, 'current obsession', 'Generative obsession (making/learning) plus specificity vs passive.', 'activation', 0.6, 'Generative obsession (making/learning) plus specificity scores high; passive consumption scores low.', ARRAY['Builder', 'Sage']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'referrals', 'Who referred you?', 'group', 'who-you-are', 6, false, true, 'who referred them', 'Referral trust. Joins referral1-3 first/last names.', 'contribution', 0.9, 'Named existing-member referrers score highest; multiple strong referrals raise contribution; vague or none scores low.', ARRAY['Connector', 'Patron', 'Host']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'cities', 'What other cities do you spend real time in?', 'short_text', 'who-you-are', 7, false, true, 'cities they move between', 'Cross-market movement - a mild reach signal.', 'activation', 0.3, 'Multi-market movement is a mild reach signal; a single home city is neutral.', ARRAY['Connector', 'Patron']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'connectionCreated', 'Tell us about a connection or opportunity you helped create for someone else.', 'long_text', 'how-you-move', 8, false, true, 'a connection they created for someone', 'CORE contribution - a concrete, consequential connection.', 'contribution', 1, 'CORE contribution. A concrete consequential connection created for someone else scores highest; hypothetical or self-serving scores low.', ARRAY['Connector', 'Patron', 'Host']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'loyalCommunity', 'Tell us about a group or community you''ve stayed loyal to - and what keeps you there?', 'long_text', 'how-you-move', 9, false, true, 'a community they stayed loyal to', 'Sustained investment in a group plus a clear reason.', 'contribution', 0.7, 'Sustained investment in a group plus a clear reason scores high; transactional membership scores low.', ARRAY['Host', 'Connector']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'goodCompany', 'How do you know when you''re in good company?', 'long_text', 'how-you-move', 10, false, true, 'how they recognize good company', 'Values centering generosity and presence vs status/access-only.', 'contribution', 0.6, 'Values centering mutual generosity and presence score high; status or access-only framing scores low.', ARRAY['Host', 'Connector']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'flowThrough', 'What kind of people, ideas, or opportunities tend to flow through your world?', 'long_text', 'what-youre-here-for', 11, false, true, 'what flows through their world', 'Network gravity - the caliber of what moves through them.', 'influence', 0.8, 'High-quality people, ideas, or opportunities flowing through their world signals network gravity; thin or self-focused answers score low.', ARRAY['Connector', 'Patron']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'investedIn', 'What''s something you''ve invested heavily in recently?', 'long_text', 'what-youre-here-for', 12, false, true, 'what they invested heavily in', 'Backing a person, project, or cause - Patron/Builder tell.', 'contribution', 0.6, 'Heavy recent investment in a person, project, or cause scores high; backing others scores above self-investment.', ARRAY['Patron', 'Builder']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'walkIntoRoom', 'You walk into a room where you don''t know anyone. What do you actually do?', 'long_text', 'how-you-move', 13, false, true, 'what they do walking into a room of strangers', 'NEUTRAL DISCRIMINATOR - behavior sorts the archetype.', 'activation', 0.9, 'NEUTRAL DISCRIMINATOR. Behavior sorts: works-the-room / first-to-talk to Spark, finds-the-person-alone to Host, maps-who-should-meet to Connector, reads-the-room-first to Sage, finds-their-person to Patron, assesses-the-space / setup to Builder. Reward specificity; generic "I mingle" scores low.', ARRAY['Connector', 'Host', 'Builder', 'Patron', 'Sage', 'Spark']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'unplannedFun', 'What''s the most fun you''ve had recently that wasn''t planned?', 'long_text', 'how-you-move', 14, false, true, 'their best unplanned recent fun', 'The say-yes instinct - ease and specificity of a spontaneous story.', 'activation', 0.6, 'Ease and specificity of a spontaneous story scores high; can''t-recall or reframed-as-planned scores low. Catches the say-yes instinct.', ARRAY['Spark']::text[], NULL, now(), now()),
  (gen_random_uuid()::text, 'cmpd6xckn000004jl47xpwghx', (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership'), 'meetPeople', 'Where do you meet new people?', 'long_text', 'how-you-move', 15, false, true, 'where they meet new people', 'Rich people-oriented sources vs thin or purely online.', 'contribution', 0.4, 'Rich people-oriented sources (hobbies, gatherings, through-friends) score high; thin or purely online scores low.', ARRAY['Connector', 'Spark']::text[], NULL, now(), now());

-- 4. Point the workspace's default template at this one (so lib/scoring.ts resolves it)
UPDATE "Workspace" SET "defaultTemplateId" = (SELECT id FROM "ApplicationTemplate" WHERE "workspaceId" = 'cmpd6xckn000004jl47xpwghx' AND slug = 'membership') WHERE id = 'cmpd6xckn000004jl47xpwghx';

COMMIT;
