-- comms-log.sql  (Slice 3 — Communicate + log it)
--
-- ADDITIVE ONLY. Generated by `prisma migrate diff` (datamodel -> datamodel vs
-- main), copy-pasted verbatim except splitting the enum ADD VALUEs into the
-- separate standalone file comms-log-enums.sql (same reason as
-- crm-consent-floor.sql/-enums.sql: ALTER TYPE ADD VALUE cannot share a txn with
-- other DDL). Adds:
--   - 2 nullable columns + 2 indexes + 2 FKs on the EXISTING SmsConversation table
--     (memberId, personId — dual-pointer identity link, Slice 0/1 pattern)
--   - 1 NEW table (TransactionalEmailLog) + its indexes + FKs
-- Touches NOTHING that already exists beyond adding the two SmsConversation
-- columns: zero DROP, zero ALTER of an existing column's type, zero RENAME. Does
-- not touch Asset_searchVector_idx, the sponsor_audience_member VIEW, any HNSW
-- index, or the live-DB-only SmsMessage.twilioSid column (not in schema.prisma,
-- not touched by this file, not affected by it — this diff was generated
-- schema-to-schema, not against a live datasource, specifically to avoid that
-- known drift leaking into the diff).
--
-- RUN (unpooled endpoint; DDL must not go through PgBouncer):
--   DATABASE_URL="$DIRECT_URL" node node_modules/prisma/build/index.js db execute \
--     --file prisma/sql/comms-log.sql --schema prisma/schema.prisma
-- Do NOT `prisma db push`. Do NOT `npx prisma`.

-- AlterTable
ALTER TABLE "SmsConversation" ADD COLUMN     "memberId" TEXT,
ADD COLUMN     "personId" TEXT;

-- CreateTable
CREATE TABLE "TransactionalEmailLog" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "templateKey" TEXT NOT NULL,
    "to" TEXT NOT NULL,
    "memberId" TEXT,
    "personId" TEXT,
    "providerId" TEXT,
    "status" TEXT NOT NULL DEFAULT 'sent',
    "sentAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "openedAt" TIMESTAMP(3),
    "clickedAt" TIMESTAMP(3),

    CONSTRAINT "TransactionalEmailLog_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "TransactionalEmailLog_workspaceId_idx" ON "TransactionalEmailLog"("workspaceId");

-- CreateIndex
CREATE INDEX "TransactionalEmailLog_memberId_idx" ON "TransactionalEmailLog"("memberId");

-- CreateIndex
CREATE INDEX "TransactionalEmailLog_personId_idx" ON "TransactionalEmailLog"("personId");

-- CreateIndex
CREATE INDEX "TransactionalEmailLog_providerId_idx" ON "TransactionalEmailLog"("providerId");

-- CreateIndex
CREATE INDEX "SmsConversation_memberId_idx" ON "SmsConversation"("memberId");

-- CreateIndex
CREATE INDEX "SmsConversation_personId_idx" ON "SmsConversation"("personId");

-- AddForeignKey
ALTER TABLE "SmsConversation" ADD CONSTRAINT "SmsConversation_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "SmsConversation" ADD CONSTRAINT "SmsConversation_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TransactionalEmailLog" ADD CONSTRAINT "TransactionalEmailLog_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TransactionalEmailLog" ADD CONSTRAINT "TransactionalEmailLog_memberId_fkey" FOREIGN KEY ("memberId") REFERENCES "Member"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "TransactionalEmailLog" ADD CONSTRAINT "TransactionalEmailLog_personId_fkey" FOREIGN KEY ("personId") REFERENCES "Person"("id") ON DELETE SET NULL ON UPDATE CASCADE;
