-- StripeEvent: Stripe webhook idempotency ledger (additive, Phase 1 of Stripe checkout hardening).
-- Generated by `prisma migrate diff` (schema-before vs schema-after). Purely additive:
-- one CREATE TABLE + 3 indexes. No DROP / ALTER TYPE / RENAME.
--
-- Apply (Adam runs this against Neon; never `prisma db push`):
--   node node_modules/prisma/build/index.js db execute --file prisma/sql/stripe-event.sql --schema prisma/schema.prisma

-- CreateTable
CREATE TABLE "StripeEvent" (
    "id" TEXT NOT NULL,
    "stripeId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "workspaceId" TEXT,
    "processedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "StripeEvent_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "StripeEvent_stripeId_key" ON "StripeEvent"("stripeId");

-- CreateIndex
CREATE INDEX "StripeEvent_type_idx" ON "StripeEvent"("type");

-- CreateIndex
CREATE INDEX "StripeEvent_processedAt_idx" ON "StripeEvent"("processedAt");
