-- ═══════════════════════════════════════════════════════════════════════════
-- Ways-In Phase A (Stage 17) — additive schema changes. 2026-07-06.
--
-- Run MANUALLY in the Neon SQL console. NEVER `prisma db push` on this repo
-- (it drops the out-of-band Asset_searchVector_idx GIN index).
--
-- ⚠ RUN THE TWO SECTIONS AS SEPARATE STATEMENTS. Postgres cannot run
--   `ALTER TYPE ... ADD VALUE` inside a transaction block with other DDL —
--   execute Section 1 on its own first, then Section 2.
-- ═══════════════════════════════════════════════════════════════════════════


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 1 — enum value (run ALONE, as its own statement)
--
-- New MemberEngagementEventType value for the one-off private-link redemption
-- fact (spec §4, name ratified). No emitter until Phase C; the enum lands now
-- so Phase C needs no DDL.
-- ─────────────────────────────────────────────────────────────────────────────

ALTER TYPE "MemberEngagementEventType" ADD VALUE IF NOT EXISTS 'access_link_redeemed';


-- ─────────────────────────────────────────────────────────────────────────────
-- SECTION 2 — EventAccessModel table (run AFTER Section 1 has committed)
--
-- The authored Ways-In document of record (spec §2.0). The gate tree is a
-- pure compile artifact regenerated from `waysIn`; `compiledTreeHash` anchors
-- the "advanced gate" (hand-edited) flag; `compiledMap` maps wayInId -> gate
-- node ids so recompiles keep node identity and guests' proofs survive edits.
-- Generated by `prisma migrate diff` and hand-reviewed: additive only —
-- no DROP, no ALTER of existing objects.
-- ─────────────────────────────────────────────────────────────────────────────

CREATE TABLE "EventAccessModel" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "eventId" TEXT NOT NULL,
    "waysIn" JSONB NOT NULL,
    "compiledTreeHash" TEXT,
    "compiledMap" JSONB,
    "compiledAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EventAccessModel_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "EventAccessModel_eventId_key" ON "EventAccessModel"("eventId");

CREATE INDEX "EventAccessModel_workspaceId_idx" ON "EventAccessModel"("workspaceId");

ALTER TABLE "EventAccessModel" ADD CONSTRAINT "EventAccessModel_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE "EventAccessModel" ADD CONSTRAINT "EventAccessModel_eventId_fkey" FOREIGN KEY ("eventId") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;
