-- RECONCILIATION CATCH-UP MIGRATION (audit-gap discovery — see data CRITICAL #3)
-- The Digital Asset Manager schema (Asset / MediaFolder / ShareLink / AssetDownload + their
-- enums, indexes, FKs) and Workspace.storageBytes were applied to the shared Neon instance via
-- raw `prisma db push` with NO prisma/sql artifact, so — unlike the 9 prisma/sql files — they
-- had no source SQL AND no tracked migration. This DDL was generated by
--   `prisma migrate diff --from-migrations <tracked> --to-schema prisma/schema.prisma --script`
-- (i.e. straight from schema.prisma = live prod), then hand-reviewed: zero DROP / ALTER TYPE /
-- RENAME, idempotent guards added. Apply via
--   `prisma migrate resolve --applied 20260526170000_media_dam_schema`
-- (writes a _prisma_migrations row only — ZERO DDL). See _context/MIGRATION-RECONCILIATION-RUNBOOK.md.
--
-- Ordered BEFORE 20260526180000_dam_search_vector: that migration adds the search-vector
-- trigger + GIN index to "Asset"."searchVector" (the tsvector column created here).

-- CreateEnum (idempotent)
DO $$ BEGIN
  CREATE TYPE "AssetFileType" AS ENUM ('PHOTO', 'VIDEO');
EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN
  CREATE TYPE "MediaFolderType" AS ENUM ('FULL_GALLERY', 'SELECTS', 'VIDEO', 'SPONSOR', 'BRAND');
EXCEPTION WHEN duplicate_object THEN null; END $$;
DO $$ BEGIN
  CREATE TYPE "ShareLinkMode" AS ENUM ('SPONSOR', 'MEMBER_GALLERY');
EXCEPTION WHEN duplicate_object THEN null; END $$;

-- AlterTable: storage accounting on Workspace
ALTER TABLE "Workspace" ADD COLUMN IF NOT EXISTS "storageBytes" BIGINT NOT NULL DEFAULT 0;

-- CreateTable
CREATE TABLE IF NOT EXISTS "Asset" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "url" TEXT NOT NULL,
    "thumbnailUrl" TEXT NOT NULL,
    "blurhash" TEXT,
    "fileType" "AssetFileType" NOT NULL,
    "size" INTEGER NOT NULL,
    "width" INTEGER,
    "height" INTEGER,
    "duration" DOUBLE PRECISION,
    "shootDate" TIMESTAMP(3),
    "tags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "aiTags" TEXT[] DEFAULT ARRAY[]::TEXT[],
    "qualityScore" DOUBLE PRECISION,
    "qualityScores" JSONB,
    "energyLevel" TEXT,
    "shooterCredit" TEXT,
    "searchVector" tsvector,
    "isSelect" BOOLEAN NOT NULL DEFAULT false,
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "folderId" TEXT,
    "eventId" TEXT,
    "sponsorName" TEXT,
    "uploadedBy" TEXT NOT NULL,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Asset_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "MediaFolder" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" "MediaFolderType" NOT NULL,
    "eventId" TEXT,
    "parentId" TEXT,
    "usageRightsExpiry" TIMESTAMP(3),
    "sortOrder" INTEGER NOT NULL DEFAULT 0,
    "deletedAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "MediaFolder_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "ShareLink" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "token" TEXT NOT NULL,
    "folderId" TEXT NOT NULL,
    "mode" "ShareLinkMode" NOT NULL,
    "password" TEXT,
    "expiresAt" TIMESTAMP(3),
    "firstAccessedAt" TIMESTAMP(3),
    "lastAccessedAt" TIMESTAMP(3),
    "accessCount" INTEGER NOT NULL DEFAULT 0,
    "brandingOverride" JSONB,
    "customDomain" TEXT,
    "watermark" BOOLEAN NOT NULL DEFAULT false,
    "allowedDownloads" INTEGER,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "ShareLink_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE IF NOT EXISTS "AssetDownload" (
    "id" TEXT NOT NULL,
    "workspaceId" TEXT NOT NULL,
    "assetId" TEXT NOT NULL,
    "shareLinkId" TEXT,
    "downloadedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "AssetDownload_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Asset_workspaceId_idx" ON "Asset"("workspaceId");
CREATE INDEX IF NOT EXISTS "Asset_folderId_idx" ON "Asset"("folderId");
CREATE INDEX IF NOT EXISTS "Asset_eventId_idx" ON "Asset"("eventId");
CREATE INDEX IF NOT EXISTS "Asset_deletedAt_idx" ON "Asset"("deletedAt");
CREATE INDEX IF NOT EXISTS "MediaFolder_workspaceId_idx" ON "MediaFolder"("workspaceId");
CREATE INDEX IF NOT EXISTS "MediaFolder_eventId_idx" ON "MediaFolder"("eventId");
CREATE INDEX IF NOT EXISTS "MediaFolder_parentId_idx" ON "MediaFolder"("parentId");
CREATE UNIQUE INDEX IF NOT EXISTS "ShareLink_token_key" ON "ShareLink"("token");
CREATE UNIQUE INDEX IF NOT EXISTS "ShareLink_customDomain_key" ON "ShareLink"("customDomain");
CREATE INDEX IF NOT EXISTS "ShareLink_workspaceId_idx" ON "ShareLink"("workspaceId");
CREATE INDEX IF NOT EXISTS "ShareLink_folderId_idx" ON "ShareLink"("folderId");
CREATE INDEX IF NOT EXISTS "AssetDownload_workspaceId_idx" ON "AssetDownload"("workspaceId");
CREATE INDEX IF NOT EXISTS "AssetDownload_assetId_idx" ON "AssetDownload"("assetId");
CREATE INDEX IF NOT EXISTS "AssetDownload_shareLinkId_idx" ON "AssetDownload"("shareLinkId");

-- AddForeignKey (catalog-guarded so fresh-build deploy + re-run are both safe)
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Asset_workspaceId_fkey') THEN
    ALTER TABLE "Asset" ADD CONSTRAINT "Asset_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'Asset_folderId_fkey') THEN
    ALTER TABLE "Asset" ADD CONSTRAINT "Asset_folderId_fkey" FOREIGN KEY ("folderId") REFERENCES "MediaFolder"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'MediaFolder_workspaceId_fkey') THEN
    ALTER TABLE "MediaFolder" ADD CONSTRAINT "MediaFolder_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'MediaFolder_parentId_fkey') THEN
    ALTER TABLE "MediaFolder" ADD CONSTRAINT "MediaFolder_parentId_fkey" FOREIGN KEY ("parentId") REFERENCES "MediaFolder"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ShareLink_workspaceId_fkey') THEN
    ALTER TABLE "ShareLink" ADD CONSTRAINT "ShareLink_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ShareLink_folderId_fkey') THEN
    ALTER TABLE "ShareLink" ADD CONSTRAINT "ShareLink_folderId_fkey" FOREIGN KEY ("folderId") REFERENCES "MediaFolder"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'AssetDownload_workspaceId_fkey') THEN
    ALTER TABLE "AssetDownload" ADD CONSTRAINT "AssetDownload_workspaceId_fkey" FOREIGN KEY ("workspaceId") REFERENCES "Workspace"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'AssetDownload_assetId_fkey') THEN
    ALTER TABLE "AssetDownload" ADD CONSTRAINT "AssetDownload_assetId_fkey" FOREIGN KEY ("assetId") REFERENCES "Asset"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'AssetDownload_shareLinkId_fkey') THEN
    ALTER TABLE "AssetDownload" ADD CONSTRAINT "AssetDownload_shareLinkId_fkey" FOREIGN KEY ("shareLinkId") REFERENCES "ShareLink"("id") ON DELETE SET NULL ON UPDATE CASCADE;
  END IF;
END $$;
