import zipData from '@/lib/data/zip-timezones.json';

/**
 * Zip -> IANA timezone lookup for quiet-hours enforcement (the send layer
 * reads this; the opt-in page only validates that the zip is known).
 *
 * ZIP-LEVEL ON PURPOSE: a state-level map is wrong for this exact list —
 * Texas splits Central/Mountain (El Paso, 799xx/885xx, is America/Denver).
 *
 * Data: lib/data/zip-timezones.json, generated by
 * scripts/vendor-zip-timezones.mjs from zipcodes@8.0.0 centroids (GeoNames-
 * derived — ZCTA-style approximations of USPS zips, not identical) crossed
 * with geo-tz@8.1.8 IANA boundaries. Stamped with sources + generation date
 * in its _meta block. Static JSON at runtime; no runtime dependency.
 */

const zips = (zipData as { zips: Record<string, string> }).zips;

/** IANA timezone for a 5-digit US zip, or null when unknown. */
export function timezoneForZip(postalCode: string | null | undefined): string | null {
  const zip = postalCode?.trim().slice(0, 5);
  if (!zip || !/^\d{5}$/.test(zip)) return null;
  return zips[zip] ?? null;
}

/** True when the zip is a known, mappable US zip. */
export function isKnownZip(postalCode: string | null | undefined): boolean {
  return timezoneForZip(postalCode) !== null;
}
